//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zorbo.Server.WPF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zorbo.Server.WPF.Resources.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string BtnClear {
            get {
                return ResourceManager.GetString("BtnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string BtnImport {
            get {
                return ResourceManager.GetString("BtnImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string BtnLoad {
            get {
                return ResourceManager.GetString("BtnLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string BtnOK {
            get {
                return ResourceManager.GetString("BtnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string BtnRemove {
            get {
                return ResourceManager.GetString("BtnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string BtnSettings {
            get {
                return ResourceManager.GetString("BtnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string BtnStart {
            get {
                return ResourceManager.GetString("BtnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string BtnStop {
            get {
                return ResourceManager.GetString("BtnStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Places.
        /// </summary>
        public static string JumpCategory {
            get {
                return ResourceManager.GetString("JumpCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string LabelAdmin {
            get {
                return ResourceManager.GetString("LabelAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load with Windows.
        /// </summary>
        public static string LabelAutoLoad {
            get {
                return ResourceManager.GetString("LabelAutoLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoStart Server.
        /// </summary>
        public static string LabelAutoStart {
            get {
                return ResourceManager.GetString("LabelAutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar.
        /// </summary>
        public static string LabelAvatar {
            get {
                return ResourceManager.GetString("LabelAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ben length.
        /// </summary>
        public static string LabelBanLength {
            get {
                return ResourceManager.GetString("LabelBanLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days (0 for unlimited).
        /// </summary>
        public static string LabelBanLengthInfo {
            get {
                return ResourceManager.GetString("LabelBanLengthInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot Name.
        /// </summary>
        public static string LabelBot {
            get {
                return ResourceManager.GetString("LabelBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Captcha.
        /// </summary>
        public static string LabelCaptcha {
            get {
                return ResourceManager.GetString("LabelCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate File.
        /// </summary>
        public static string LabelCertFile {
            get {
                return ResourceManager.GetString("LabelCertFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Pass.
        /// </summary>
        public static string LabelCertPass {
            get {
                return ResourceManager.GetString("LabelCertPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string LabelClose {
            get {
                return ResourceManager.GetString("LabelClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Name.
        /// </summary>
        public static string LabelDomain {
            get {
                return ResourceManager.GetString("LabelDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string LabelFind {
            get {
                return ResourceManager.GetString("LabelFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string LabelHost {
            get {
                return ResourceManager.GetString("LabelHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LabelLanguage {
            get {
                return ResourceManager.GetString("LabelLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAN users are Host.
        /// </summary>
        public static string LabelLANUsers {
            get {
                return ResourceManager.GetString("LabelLANUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string LabelLevel {
            get {
                return ResourceManager.GetString("LabelLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max clients.
        /// </summary>
        public static string LabelMaxClients {
            get {
                return ResourceManager.GetString("LabelMaxClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max clones.
        /// </summary>
        public static string LabelMaxClones {
            get {
                return ResourceManager.GetString("LabelMaxClones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderator.
        /// </summary>
        public static string LabelModerator {
            get {
                return ResourceManager.GetString("LabelModerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LabelPluginName {
            get {
                return ResourceManager.GetString("LabelPluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Plugins.
        /// </summary>
        public static string LabelPlugins {
            get {
                return ResourceManager.GetString("LabelPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string LabelPluginState {
            get {
                return ResourceManager.GetString("LabelPluginState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string LabelPort {
            get {
                return ResourceManager.GetString("LabelPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Channel.
        /// </summary>
        public static string LabelShowChannel {
            get {
                return ResourceManager.GetString("LabelShowChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string LabelSize {
            get {
                return ResourceManager.GetString("LabelSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start server.
        /// </summary>
        public static string LabelStartServer {
            get {
                return ResourceManager.GetString("LabelStartServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop server.
        /// </summary>
        public static string LabelStopServer {
            get {
                return ResourceManager.GetString("LabelStopServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use TCP Sockets.
        /// </summary>
        public static string LabelTCPSockets {
            get {
                return ResourceManager.GetString("LabelTCPSockets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use TLS Sockets.
        /// </summary>
        public static string LabelTLSSockets {
            get {
                return ResourceManager.GetString("LabelTLSSockets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic.
        /// </summary>
        public static string LabelTopic {
            get {
                return ResourceManager.GetString("LabelTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use UDP Sockets.
        /// </summary>
        public static string LabelUDPSockets {
            get {
                return ResourceManager.GetString("LabelUDPSockets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL Address.
        /// </summary>
        public static string LabelUrlAddress {
            get {
                return ResourceManager.GetString("LabelUrlAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL Caption.
        /// </summary>
        public static string LabelUrlCaption {
            get {
                return ResourceManager.GetString("LabelUrlCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Web Sockets.
        /// </summary>
        public static string LabelWebSockets {
            get {
                return ResourceManager.GetString("LabelWebSockets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string SettingsChat {
            get {
                return ResourceManager.GetString("SettingsChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string SettingsGeneral {
            get {
                return ResourceManager.GetString("SettingsGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logins.
        /// </summary>
        public static string SettingsLogin {
            get {
                return ResourceManager.GetString("SettingsLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        public static string SettingsNetwork {
            get {
                return ResourceManager.GetString("SettingsNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        public static string SettingsPlugins {
            get {
                return ResourceManager.GetString("SettingsPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TLS / SSL.
        /// </summary>
        public static string SettingsTLS {
            get {
                return ResourceManager.GetString("SettingsTLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banned Users.
        /// </summary>
        public static string StatBanned {
            get {
                return ResourceManager.GetString("StatBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        public static string StatNetwork {
            get {
                return ResourceManager.GetString("StatNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins Loaded.
        /// </summary>
        public static string StatPlugins {
            get {
                return ResourceManager.GetString("StatPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banned Ranges.
        /// </summary>
        public static string StatRanges {
            get {
                return ResourceManager.GetString("StatRanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers Loaded.
        /// </summary>
        public static string StatServers {
            get {
                return ResourceManager.GetString("StatServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string StatUsers {
            get {
                return ResourceManager.GetString("StatUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zorbo - Add New Login.
        /// </summary>
        public static string TitleLogins {
            get {
                return ResourceManager.GetString("TitleLogins", resourceCulture);
            }
        }
    }
}
