//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zorbo.Ares.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zorbo.Ares.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are banned from this chatroom.
        /// </summary>
        public static string Banned {
            get {
                return ResourceManager.GetString("Banned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many connections from: {0}.
        /// </summary>
        public static string Clones {
            get {
                return ResourceManager.GetString("Clones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your dns name is banned from this chatroom.
        /// </summary>
        public static string DnsBanned {
            get {
                return ResourceManager.GetString("DnsBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait a minute before joining.
        /// </summary>
        public static string Flooding {
            get {
                return ResourceManager.GetString("Flooding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or malicious login attempt.
        /// </summary>
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been disconnected for login flooding.
        /// </summary>
        public static string LoginFlood {
            get {
                return ResourceManager.GetString("LoginFlood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already in use in this chatroom.
        /// </summary>
        public static string NameTaken {
            get {
                return ResourceManager.GetString("NameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your IP range is banned from this chatroom.
        /// </summary>
        public static string RangeBanned {
            get {
                return ResourceManager.GetString("RangeBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A plugin has denied you entry to this chatroom.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
    }
}
