//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zorbo.Ares.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zorbo.Ares.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are muzzled {0}.
        /// </summary>
        public static string AreMuzzled {
            get {
                return ResourceManager.GetString("AreMuzzled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} has been banned.
        /// </summary>
        public static string Banned {
            get {
                return ResourceManager.GetString("Banned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been banned for too many invalid answers.
        /// </summary>
        public static string BannedCaptchaAnswers {
            get {
                return ResourceManager.GetString("BannedCaptchaAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been banned for not answering within 2 hours of connecting.
        /// </summary>
        public static string BannedCaptchaTimeout {
            get {
                return ResourceManager.GetString("BannedCaptchaTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zorbo.
        /// </summary>
        public static string DefaultBotName {
            get {
                return ResourceManager.GetString("DefaultBotName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zorbo Server.
        /// </summary>
        public static string DefaultName {
            get {
                return ResourceManager.GetString("DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to my Zorbo Server!.
        /// </summary>
        public static string DefaultTopic {
            get {
                return ResourceManager.GetString("DefaultTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have ignored messages from {0}.
        /// </summary>
        public static string Ignored {
            get {
                return ResourceManager.GetString("Ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your answer is incorrect, {0} tries remaining.
        /// </summary>
        public static string InvalidCaptcha {
            get {
                return ResourceManager.GetString("InvalidCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password supplied is invalid.
        /// </summary>
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been logged in as {0}.
        /// </summary>
        public static string LoggedIn {
            get {
                return ResourceManager.GetString("LoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been logged out of administrator.
        /// </summary>
        public static string LoggedOut {
            get {
                return ResourceManager.GetString("LoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been muzzled.
        /// </summary>
        public static string Muzzled {
            get {
                return ResourceManager.GetString("Muzzled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been registered.
        /// </summary>
        public static string Registered {
            get {
                return ResourceManager.GetString("Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have allowed messages from {0}.
        /// </summary>
        public static string Unignored {
            get {
                return ResourceManager.GetString("Unignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been unmuzzled.
        /// </summary>
        public static string Unmuzzled {
            get {
                return ResourceManager.GetString("Unmuzzled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.3.0.0.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zorbo 0.3.0 Alpha.
        /// </summary>
        public static string VersionChannels {
            get {
                return ResourceManager.GetString("VersionChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zorbo 0.3.0 Alpha.
        /// </summary>
        public static string VersionLogin {
            get {
                return ResourceManager.GetString("VersionLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have joined vroom {0}.
        /// </summary>
        public static string VroomNotice {
            get {
                return ResourceManager.GetString("VroomNotice", resourceCulture);
            }
        }
    }
}
