using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace cb0tProtocol
{
    public enum AdvancedId
    {
        MSG_CHAT_CLIENT_CUSTOM_ADD_TAGS = 202,
        MSG_CHAT_CLIENT_CUSTOM_REM_TAGS = 203,
        MSG_CHAT_CLIENT_CUSTOM_FONT = 204,
        MSG_CHAT_SERVER_CUSTOM_FONT = 204,
        MSG_CHAT_CLIENT_VC_SUPPORTED = 205,
        MSG_CHAT_SERVER_VC_SUPPORTED = 205,
        MSG_CHAT_CLIENT_VC_FIRST = 206,
        MSG_CHAT_SERVER_VC_FIRST = 206,
        MSG_CHAT_SERVER_VC_FIRST_FROM = 207,
        MSG_CHAT_CLIENT_VC_FIRST_TO = 207,
        MSG_CHAT_SERVER_VC_CHUNK = 208,
        MSG_CHAT_CLIENT_VC_CHUNK = 208,
        MSG_CHAT_CLIENT_VC_CHUNK_TO = 209,
        MSG_CHAT_SERVER_VC_CHUNK_FROM = 209,
        MSG_CHAT_SERVER_VC_IGNORE = 210,
        MSG_CHAT_CLIENT_VC_IGNORE = 210,
        MSG_CHAT_SERVER_VC_NOPVT = 211,
        MSG_CHAT_SERVER_VC_USER_SUPPORTED = 212,
        MSG_CHAT_SERVER_SUPPORTS_CUSTOM_EMOTES = 220,
        MSG_CHAT_CLIENT_SUPPORTS_CUSTOM_EMOTES = 220,
        MSG_CHAT_SERVER_CUSTOM_EMOTES_ITEM = 221,
        MSG_CHAT_CLIENT_CUSTOM_EMOTES_UPLOAD_ITEM = 221,
        MSG_CHAT_SERVER_CUSTOM_EMOTE_DELETE = 222,
        MSG_CHAT_CLIENT_CUSTOM_EMOTE_DELETE = 222,
        MSG_CHAT_SERVER_ROOM_SCRIBBLE = 225,
        MSG_CHAT_CLIENT_ROOM_SCRIBBLE_FIRST = 240,
        MSG_CHAT_CLIENT_ROOM_SCRIBBLE_CHUNK = 241,
        MSG_CHAT_ADVANCED_FEATURES_PROTOCOL = 250,
    }
}
